name: 'k8s cluster Preview Environments'
description: 'k8s cluster Preview Environments for every pull request. Supports APIs, frontends, backends, databases, and microservices.'
author: 'Vibhav Bobade'
branding:
  color: 'yellow'
  icon: 'upload-cloud'
inputs:
  server:
    description: 'URL to Uffizzi'
    required: true
    default: 'https://app.uffizzi.com'
  username:
    description: 'Uffizzi username'
    required: false
  password:
    description: 'Uffizzi password'
    required: false
  project:
    description: 'Uffizzi project slug'
    required: false
  cluster-name:
    description: 'Name of the Uffizzi cluster which is going to get created'
    required: false

runs:
  using: 'composite'
  steps:
  - shell: bash
    env:
      UFFIZZI_PASSWORD: ${{ inputs.password }}
      UFFIZZI_SERVER: ${{ inputs.server }}
      UFFIZZI_USER: ${{ inputs.username }}
      UFFIZZI_PROJECT: ${{ inputs.project }}
      UFFIZZI_CLUSTER: ${{ inputs.cluster-name }}
      UFFIZZI_IMAGE: uffizzi/cli:pr-224
    run: |
      # Identify if a Cluster for this PR exists.
      if docker run --rm \
        --env UFFIZZI_SERVER=${UFFIZZI_SERVER} \
        --env UFFIZZI_USER=${UFFIZZI_USER} \
        --env UFFIZZI_PASSWORD=${UFFIZZI_PASSWORD} \
        --env UFFIZZI_PROJECT=${UFFIZZI_PROJECT} \
        ${UFFIZZI_IMAGE} cluster list | grep --quiet ${UFFIZZI_CLUSTER}
      then
        # If it already exists, fetch the `kubeconfig` to connect to it.
        docker run --rm --env UFFIZZI_SERVER=${UFFIZZI_SERVER} \
          --env UFFIZZI_USER=${UFFIZZI_USER} \
          --env UFFIZZI_PASSWORD=${UFFIZZI_PASSWORD} \
          --env UFFIZZI_PROJECT=${UFFIZZI_PROJECT} \
          --mount type=bind,source="$(pwd)",target=/home \
          ${UFFIZZI_IMAGE} cluster update-kubeconfig \
          --name ${UFFIZZI_CLUSTER} --kubeconfig /home/kubeconfig
      else
        # Create the Cluster if it does not yet exist.
        docker run --rm --env UFFIZZI_SERVER=${UFFIZZI_SERVER} \
          --env UFFIZZI_USER=${UFFIZZI_USER} \
          --env UFFIZZI_PASSWORD=${UFFIZZI_PASSWORD} \
          --env UFFIZZI_PROJECT=${UFFIZZI_PROJECT} \
          --mount type=bind,source="$(pwd)",target=/home \
        ${UFFIZZI_IMAGE} cluster create \
          --name ${UFFIZZI_CLUSTER} --kubeconfig /home/kubeconfig
        echo "::set-output name=kubeconfig::$(cat /home/kubeconfig)"
      fi

  # - name: Move kubeconfig artifact
  #   run: |
  #     mv /home/kubeconfig ${{ github.workspace }}/kubeconfig
  #   shell: bash

  # - name: Upload kubeconfig artifact
  #   uses: actions/upload-artifact@v3
  #   with: 
  #     name: kubeconfig
  #     path: ${{ github.workspace }}/kubeconfig
