name: 'k8s cluster Preview Environments'
description: 'k8s cluster Preview Environments for every pull request. Supports APIs, frontends, backends, databases, and microservices.'
author: 'Vibhav Bobade'
branding:
  color: 'yellow'
  icon: 'upload-cloud'
inputs:
  server:
    description: 'URL to Uffizzi'
    required: true
    default: 'https://app.uffizzi.com'
  # username:
  #   description: 'Uffizzi username'
  #   required: false
  # password:
  #   description: 'Uffizzi password'
  #   required: false
  # project:
  #   description: 'Uffizzi project slug'
  #   required: false
  cluster-name:
    description: 'Name of the Uffizzi cluster which is going to get created'
    required: false
  image:
    description: 'Uffizzi CLI image'
    default: docker.io/uffizzi/cli:pr-239
    required: true

runs:
  using: 'composite'
  steps:
  - shell: bash
    env:
      # UFFIZZI_PASSWORD: ${{ inputs.password }}
      UFFIZZI_SERVER: ${{ inputs.server }}
      # UFFIZZI_USER: ${{ inputs.username }}
      # UFFIZZI_PROJECT: ${{ inputs.project }}
      UFFIZZI_CLUSTER: ${{ inputs.cluster-name }}
      UFFIZZI_IMAGE: ${{ inputs.image }} 
    run: |
      # Identify if a Cluster for this PR exists.
      if docker run --rm \
        --env UFFIZZI_SERVER=${UFFIZZI_SERVER} \
        --env REQUEST_TOKEN=${ACTIONS_ID_TOKEN_REQUEST_TOKEN} \
        --env REQUEST_TOKEN_URL=${ACTIONS_ID_TOKEN_REQUEST_URL} \
        ${UFFIZZI_IMAGE} cluster list | grep --quiet ${UFFIZZI_CLUSTER}
      then
        # If it already exists, fetch the `kubeconfig` to connect to it.
        docker run --rm --env UFFIZZI_SERVER=${UFFIZZI_SERVER} \
          --env REQUEST_TOKEN=${ACTIONS_ID_TOKEN_REQUEST_TOKEN} \
          --env REQUEST_TOKEN_URL=${ACTIONS_ID_TOKEN_REQUEST_URL} \
          --mount type=bind,source="$(pwd)",target=/home \
        ${UFFIZZI_IMAGE} cluster update-kubeconfig \
          --name=${UFFIZZI_CLUSTER} --kubeconfig="/home/kubeconfig"
      else
        # Create the Cluster if it does not yet exist.
        docker run --rm --env UFFIZZI_SERVER=${UFFIZZI_SERVER} \
          --env REQUEST_TOKEN=${ACTIONS_ID_TOKEN_REQUEST_TOKEN} \
          --env REQUEST_TOKEN_URL=${ACTIONS_ID_TOKEN_REQUEST_URL} \
          --mount type=bind,source="$(pwd)",target=/home \
        ${UFFIZZI_IMAGE} cluster create \
          --name=${UFFIZZI_CLUSTER} --kubeconfig="/home/kubeconfig"
        echo "Uffizzi Cluster \`${UFFIZZI_CLUSTER}\` created." >> $GITHUB_STEP_SUMMARY
        export KUBERNETES_SERVICE_HOST=`yq '.clusters[0].cluster.server' < ./kubeconfig | cut -d'/' -f3`
        echo "Available at \`${KUBERNETES_SERVICE_HOST}\`." >> $GITHUB_STEP_SUMMARY
        echo "Waiting for $KUBERNETES_SERVICE_HOST"
      fi
