name: 'k8s cluster Preview Environments'
description: 'k8s cluster Preview Environments for every pull request. Supports APIs, frontends, backends, databases, and microservices.'
author: 'Vibhav Bobade'
branding:
  color: 'yellow'
  icon: 'upload-cloud'
inputs:
  server:
    description: 'URL to Uffizzi'
    required: true
    default: 'https://app.uffizzi.com'
  username:
    description: 'Uffizzi username'
    required: false
  password:
    description: 'Uffizzi password'
    required: false
  project:
    description: 'Uffizzi project slug'
    required: false
  cluster-name:
    description: 'Name of the Uffizzi cluster which is going to get created'
    required: false
  image:
    description: 'Uffizzi CLI image'
    default: docker.io/uffizzi/cli:pr-239
    required: true
  operation:
    description: 'Specification for the operation on the cluster. Whether it needs to be created, deleted or updated.'
    default: 'create'
    required: true

runs:
  using: 'composite'
  steps:
  - shell: bash
    env:
      UFFIZZI_PASSWORD: ${{ inputs.password }}
      UFFIZZI_SERVER: ${{ inputs.server }}
      UFFIZZI_USER: ${{ inputs.username }}
      UFFIZZI_PROJECT: ${{ inputs.project }}
      UFFIZZI_CLUSTER: ${{ inputs.cluster-name }}
      UFFIZZI_IMAGE: ${{ inputs.image }} 
      UFFIZZI_OP: ${{ inputs.operation }}
    run: .github/workflows/script.sh $UFFIZZI_OP
