name: 'k8s cluster Preview Environments'
description: 'k8s cluster Preview Environments for every pull request. Supports APIs, frontends, backends, databases, and microservices.'
author: 'Vibhav Bobade'
branding:
  color: 'yellow'
  icon: 'upload-cloud'
inputs:
  server:
    description: 'URL to Uffizzi'
    required: false
    default: 'https://app.uffizzi.com'
  cluster-name:
    description: 'Name of the Uffizzi cluster which is going to get created'
    required: true
  image:
    description: 'Uffizzi CLI image'
    default: docker.io/uffizzi/cli:v2
    required: false
  kubeconfig:
    description: 'Path to kubeconfig file.'
    default: ${{ github.workspace }}/kubeconfig
    required: false

runs:
  using: 'composite'
  steps:
  - shell: bash
    env:
    run: |
      # Identify if a Cluster for this PR exists.
      if docker run --rm \
        --env UFFIZZI_SERVER="${{ inputs.server }}" \
        --env REQUEST_TOKEN=${ACTIONS_ID_TOKEN_REQUEST_TOKEN} \
        --env REQUEST_TOKEN_URL=${ACTIONS_ID_TOKEN_REQUEST_URL} \
        "${{ inputs.image }}" cluster list | grep --quiet '^- ${{ inputs.cluster-name }}$'
      then
        # If it already exists, fetch the `kubeconfig` to connect to it.
        docker run --rm --env UFFIZZI_SERVER="${{ inputs.server }}" \
          --env REQUEST_TOKEN=${ACTIONS_ID_TOKEN_REQUEST_TOKEN} \
          --env REQUEST_TOKEN_URL=${ACTIONS_ID_TOKEN_REQUEST_URL} \
          --mount type=bind,source="$(pwd)",target=/root \
          "${{ inputs.image }}" cluster update-kubeconfig \
          --name "${{ inputs.cluster-name }}" --kubeconfig /root/kubeconfig
      else
        # Create the Cluster if it does not yet exist.
        docker run --rm --env UFFIZZI_SERVER="${{ inputs.server }}" \
          --env REQUEST_TOKEN=${ACTIONS_ID_TOKEN_REQUEST_TOKEN} \
          --env REQUEST_TOKEN_URL=${ACTIONS_ID_TOKEN_REQUEST_URL} \
          --mount type=bind,source="$(pwd)",target=/root \
        "${{ inputs.image }}" cluster create \
          --name "${{ inputs.cluster-name }}" --kubeconfig /root/kubeconfig
      fi

      mv ./kubeconfig "${{ inputs.kubeconfig }}"
